---
version: "2.1"

networks:
  plexnet: # custom network for plex media server
    external: true
    
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr # always pull the latest image unless you want a custom one
    container_name: sonarr
    environment:
      - PUID=0 # change this to your docker runner user, default to admin (bad)
      - PGID=0 # change this to your docker runner group, default to admin (bad)
      - TZ=Europe/London
    volumes:
      - /AppData/Sonarr/config:/config
      - /Multimedia/TV:/tv # linking the docker directory to your server directory, change BEFORE the colon :
      - /Multimedia/Downloads:/downloads # linking the docker directory to your server directory, change BEFORE the colon :
    ports:
      - 8989:8989 # Web portal will be accessible on http://host:8989
    networks:
      - plexnet
    deploy: # limits the amount of resource that sonarr can use, i find 128M of RAM good enough
      resources:
          limits:
            cpus: 0.50
            memory: 1000M 
    restart: unless-stopped # if we crash, restart