---
version: "2.1"

networks:
  plexnet: # custom network for plex media server
    external: true

services:
  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=100 # change this to your docker runner user
      - PGID=100 # change this to your docker runner group
      - TZ=Europe/London
      - AUTO_UPDATE=true #optional
      #- RUN_OPTS=<run options here> #optional
    volumes:
      - /AppData/Jackett/config:/config # linking the docker directory to your server directory, change BEFORE the colon :
      - /AppData/Jackett/blackhole:/downloads # linking the docker directory to your server directory, change BEFORE the colon :
    ports:
      - 9117:9117 # Web portal will be accessible on http://host:9117
    networks:
      - plexnet
    deploy: # limits the amount of resource that jackett can use, i find 128M of RAM good enough
      resources:
          limits:
            cpus: 0.10
            memory: 128M 
    restart: unless-stopped # if we crash, restart